version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: Japan
    open-pull-requests-limit: 10
    reviewers:
      - shippokun
    labels:
      - dependencies
    versioning-strategy: lockfile-only
    commit-message:
      prefix: "patch-chore: "
