development:
  adapter: mysql2
  encoding: utf8
  database: rails_development
  pool: 5
  username: root
  password: ""
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: sample_mysql_test
  pool: 5
  username: root
  password: ""
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: sample_mysql_production
  pool: 5
  username: ""
  password:
  host: localhost
